### PR TITLE
scope!

### PR DESCRIPTION
**Pull request by piever**

### CODE REVIEW

**Comment by shashi** [comment]
Looking perfect :100:

**Comment by shashi** [comment]
IMO depending on LatexStrings and re-exporting the `L""` macro in Interact and here is totally worth it.

**Comment by piever** [comment]
OK, merging here.

> IMO depending on LatexStrings and re-exporting the L"" macro in Interact and here is totally worth it.

I think so too (mainly in Interact, as it is the metapackage). The main inconvenience as we were discussing in the other thread is that LatexStrings outputs strings with dollars wrapping equations, do you think your code in CSSUtli can take care of that? Ref: https://github.com/JuliaGizmos/WebIO.jl/issues/247#issuecomment-479066793

**Comment by piever** [comment]
Yes, the CSSUtli code seems to have everything. So in practice we just require users to do:

```julia
myequation = L"$1+1$ and $c = \frac{1}[2}$"
WebIO.render(md"My equations are $myequation")
```

An things should just work. I'll wait for the switch to the new system to register a new version here and then we can try to port CSSUtil to use this one and check that everything works, dollar signs get cleared out correctly etcetera.

**Pull request merged**
